### ISSUE TITLE
问一下生成SPWM数据表的软件是什么

### ISSUE THREAD

**Issue by shi-linyu** [Li-Xiao-Chao/STM32-SPWM#1]
问一下生成SPWM数据表的软件是什么

**Comment by Li-Xiao-Chao** [comment]
https://www.microsoft.com/store/productId/9NBLGGH43H8X
实用电子工具箱

**Comment by Li-Xiao-Chao** [comment]
微软商城中的实用电子工具箱
[image0.png]

发自我的 iPad

在 2023年4月23日，11:04，shi-linyu ***@***.***> 写道：

﻿

Closed #1<https://github.com/Li-Xiao-Chao/STM32-SPWM/issues/1> as completed.
